# <font color = 'dodgerblue'> **Introduction**
* One of the basic fundamental process in data science is efficient
storage and manipulation of numerical arrays.
* The special packages to handle these numerical arrays in python are Numpy and pandas.
* In this notebook, we will explore Numpy package.


# <font color = 'dodgerblue'> **Numpy**
* Numpy stands for numerical python.
* It provides efficient way to store and manipulate arrays.
* It also contains useful linear algebra and random number functions




## <font color = 'dodgerblue'> **Importing a pacakge** </font>

1.  Python has a way to put definitions in a file and use them in your program. Such a file is called a module.
2. We use import statement to acquire the definitions from a module or the whole module.
3. We can import modules from packages using the dot (.) operator.
3. **Syntax**:
    
  ```
  import package_name as alias name
  ```
  Import statement allows to import all the definitions from the given package.

  "Alias name" can be used to give a short name for the packages.


In [1]:
# Importing numpy package
import numpy as np


## <font color = 'dodgerblue'> **Version  of Numpy**
* If there is any prerequisite of package version for any data science project, then its essential to verify the package version.
*  We can check the package version as follows `package.__version__`
   

In [2]:
# Check the version of the numpy

print(np.__version__)

1.25.2


In [ ]:
# set printion option for the notebook
np.set_printoptions()

# <font color = 'dodgerblue'> **Creating Numpy Arrays** </font>
There are 3 ways for creating arrays by using numpy and they are:

1. Conversion from other Python structures (e.g., lists, tuples)

2. Intrinsic numpy array creation objects (e.g., arange, ones, zeros, etc.)

5. Use of special library functions (e.g., random)

## <font color = 'dodgerblue'> **Conversion from other python structures using np.array()**

We can easily convert any iterable function such as lists, tuples etc. into arrays by using numpy packages.

  **Syntax**:
  ```
  np.array(list)
  np.array(tuple)

  ```
We can pass iterable functions as an argument for the array() method in numpy.


In [5]:
# Creating array from a list
# creae a numpy array from list
lists =[1,2,3]

np.array(lists,dtype = 'float')

array([1., 2., 3.])

In [6]:
# Creating arrays from tuple
lists =(1,2,3)

np.array(lists,dtype = 'float')

array([1., 2., 3.])

In [9]:
# Creating 1 dimensional array from numpy package
lists =[1,2,3]

np.array(lists,dtype = 'float')

array([1., 2., 3.])

In [12]:
# Creating 2 dimensional array from numpy package

np.array([[1,2,3],[1,2,3]],dtype="float")

array([[1., 2., 3.],
       [1., 2., 3.]])

## <font color = 'dodgerblue'> **Notation**

* In NumPy, each dimension is called an **axis**.
* The number of axes is called the **rank**.
    * For example, the above 2x2 matrix is an array of rank 2 (it is 2-dimensional).
    * The first axis has length 2, the second has length 4.
*  shape gives the size of each dimensions in an array.
    * For example, the above array's shape is `(2, 4)`.
    * The rank is equal to the shape's length.
* The **size** of an array is the total number of elements, which is the product of all axis lengths (eg. 2*4=8)

## <font color = 'dodgerblue'> **Intrinsic numpy array creation objects**
Numpy has a special built in function to create arrays from the scratch.




### <font color = 'dodgerblue'> **np.zeros**
An array filled with zeros can be created by specifying particular shape and data type. The default datatype is **float64**.
  
 **Syntax** :
  ```
   np.zeros(shape, dtype)
  ```

In [18]:
# Creating a one dimensional array filled with zeros
np.zeros((1),float),np.zeros(1,float)


(array([0.]), array([0.]))

In [ ]:
# Creating a two dimensional array filled with zeros
# The following will have 2 rows and 3 columns
np.zeros((2,3),float)

### <font color = 'dodgerblue'> **np.ones**
 An array filled with only ones can be created by specifying particular shape and data type. The default shape is **float64**.
  
  **Syntax**:
  ```
  np.ones(shape, dtype)
  ```
  where, dtype can be used as int, float etc.

In [20]:
# Creating a 1 dimensional array using ones method
np.ones(10,float)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [22]:
# Creating a 2 dimensional array using ones method.
# The following array will have 3 rows and 2 columns
np.ones((2,3),float)

array([[1., 1., 1.],
       [1., 1., 1.]])

### <font color = 'dodgerblue'>**np.full()**
We can create  an array of the given shape initialized with any given value.

 **Syntax** :
  ```
   np.full(shape, fill_value, dtype)
  ```

In [28]:
np.full((10,10),-999)

array([[-999, -999, -999, -999, -999, -999, -999, -999, -999, -999],
       [-999, -999, -999, -999, -999, -999, -999, -999, -999, -999],
       [-999, -999, -999, -999, -999, -999, -999, -999, -999, -999],
       [-999, -999, -999, -999, -999, -999, -999, -999, -999, -999],
       [-999, -999, -999, -999, -999, -999, -999, -999, -999, -999],
       [-999, -999, -999, -999, -999, -999, -999, -999, -999, -999],
       [-999, -999, -999, -999, -999, -999, -999, -999, -999, -999],
       [-999, -999, -999, -999, -999, -999, -999, -999, -999, -999],
       [-999, -999, -999, -999, -999, -999, -999, -999, -999, -999],
       [-999, -999, -999, -999, -999, -999, -999, -999, -999, -999]])

### <font color = 'dodgerblue'> **np.arange()**
arange() method is used to create values in the array in an increasing order. It is similar to the built in python range() method.

 **Syntax** :
```
np.arange(stop, dtype)
np.arange(start, stop, dtype)
np.arange(start, stop, step, dtype)
```
where,

> **start** - 	Optional. An integer number specifying the strat position. Default is 0

> **stop** - Required. An integer number specifying the stop position (**not included**).

> **step (Optional)** - Optional. An integer value which determines the increment. default is 1

In [37]:
# Creating an array using arange() method
np.arange(10,51,2)
# It will give an array starting from default 0 to 9 elements
np.arange(0,10)
# It will give an array starting from 12 and end at 24
np.arange(12,25)
# It will give an array starting from 12 ,ending at 29 and incrementing each element by 5
np.arange(12,30,5)

array([12, 17, 22, 27])

### <font color = 'dodgerblue'> **np.linspace()**

It creates evenly spaced numbers over a specified interval

  **Syntax**:

  ```
  np.linspace(start, stop, num)
  ```
  - start: strating value of sequence
  - end: end value of sequence
  - num: number of values to be generated

In [45]:
# create an array using np.linspace
np.linspace(0,100,10)
# create 10 evenly soaced values between 0 and 4
np.linspace(0,4,10)

array([0.        , 0.44444444, 0.88888889, 1.33333333, 1.77777778,
       2.22222222, 2.66666667, 3.11111111, 3.55555556, 4.        ])

### <font color = 'dodgerblue'> **eye()**
This  method can be used to create an identity matrix or array.
  * An **identity matrix** is a matrix which does not change any array when we multiply (matrix multiplication) the array with that matrix.
  * The principal diagonal elements are ones and all other elements are zeros.

 **Example**:
  $$\begin{bmatrix} 1 & 0 & 0 \\ 0 & 1 & 0 \\ 0 & 0 & 1 \end{bmatrix}$$


  **Syntax**:


  ```
  np.eye(shape of the array, dtype)
  ```
  It gives a square matrix where rows and columns are same and we can define data type as int, float etc.

In [47]:
# Using eye() method to create an identity matrix or array
# The following matrix has 5 rows and 5 columns
np.eye(5,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## <font color = 'dodgerblue'> **Special library functions**

### <font color = 'dodgerblue'>**np.random()**

numpy.random() method can be used to generate array with random numbers.


  **Syntax**:
```
    np.random.randint(start, end, shape of array) # random integers
    np.random.uniform(start, end, shape of array) # random numbers from uniform distribution
    np.random.normal(mean, standard deviation, shape) # random numbers from normal distribution

```



#### <font color = 'dodgerblue'> **Random integers - randint()**

In [ ]:
# Create an array that has random numbers (integers) between 0 to 10 in an array
# The array will consist of 3 rows and 3 columns
# the command below will also give the same result
# when we specify only one paramter then it stats from 0 till that value

#### <font color = 'dodgerblue'> **Normal Distribution - normal()**

In [ ]:
# Create an array normally distributed values
# with mean = 2 and standard deviation = 3

#### <font color = 'dodgerblue'> **Random Numbers - Uniform DIstributon - uniform()**

In [ ]:
# To create an array of uniformly distributed values.
# random values between 0 and 1

#### <font color = 'dodgerblue'> **Set Seed - seed()**

* numpy.random.seed() can be used to initialize random number generators. This will help us to generate same set of random  numbers everytie we run our code.

  **Syntax**


```
    numpy.random.seed()
    numpy.random.randint(start,stop)
```
* We can pass any integer in the seed argument.
* Then we can generate a random number which will be same all the time.

In [ ]:
# Using seed() function to generate the random numbers
# We can run this cell multiple times and we can get same random number
# if we comment the first statement (below) then we will get different number everytime we run this cell.

# <font color = 'dodgerblue'> **List arrays vs Numpy arrays**
- Arrays can store data more compactly.
- Lists cannot directly handle math operations whereas Numpy arrays are great for numerical operations.
- Appending elements to Numpy array will take more time than lists. Lists are good for the scenario where items can grow dynamically.

In the example below, we will now compare the addition of two large collections using numpy and python list.

In [ ]:
# manipulating 10 million items
# Wrrite a function to calculate time to add two arrays of 10 million items
# We will use np.arange function to generate numpy arrays
# use time() function from time module
    # time in seconds
    # generating numpy array with 10 million items
    # generating another numpy array with 10 million items
# Wrrite a sumilar function using python list
# We will use built in range function to generate list of 10 million items
# use time() function from time module
    # time in seconds
    # generating a list with 10 million items
    # generating another list with  10 million items
    # using list comprehension to add elements in two  lists

In [ ]:
# We can check the time difference between array addition by using numpy and list

# <font color = 'dodgerblue'> **Numpy operations** </font>
1. Numpy operations are used to manipulate or perform various types of mathematical operations on  the arrays.

2. Few of the numpy operations are ndim, itemsize(), dtype(), reshape(), slicing(), linspace(), min/max(), sum(), sqrt()/std(), hsatck/vstack(), etc.

3. These numpy operations can be classified as follows:
  * Attributes of arrays
  * Indexing of arrays
  * Slicing of arrays
  * Reshaping of arrays
  * Joining and splitting of arrays

## <font color = 'dodgerblue'> **Attributes of arrays**

Attributes of arrays helps in :-
*  Determining the size and shape of arrays
* Memory consumption by the arrays.  
* Different data types of arrays.



### <font color = 'dodgerblue'> **Determining the shape of the array** </font>
1. For any kind of computations or operations on an array, it is very important to understand what an array’s “shape” is.
2. shape, ndim, size are the methods used to determine the shape of the arrays.

* **ndim** : It is used to determine the dimension of an array.  **Example** : an array can be of 1 dimensional, 2 dimensional , 3 dimensional etc.

  **Syntax**:


  ```
      ndarray.ndim
  ```
  where, ndarray is the name of the array

* **shape** : It is used to determine the number of elements in each dimensions in an array. **Example** : if an array is 2 dimensional then it will consist of(number of rows, number of columns) as shape.
The output of the shape is always mentioned in a tuple form.

  **Syntax**:
  
   ```
   ndarray.shape
   ```
  where, ndarray is the name of the array
* **size** : It determines the total size of  the array. **Example**: if an array consists of 60 elements in it. Then the size of the array is the total number of elements in an array and it will be 60.

 **Syntax**:


  ```
    ndarray.size
  ```
  where, ndarray is the name of the array





#### <font color = 'dodgerblue'> **ndim**

In [ ]:
#To find the dimensions in an array

#### <font color = 'dodgerblue'> **shape**

In [ ]:
# To find  the shape of the array
# If an array is one dimensional then it presents the number of elements as a size followed by a comma(,)

#### <font color = 'dodgerblue'> **size**

In [ ]:
# To find the size of the array
# Size determines the number of elements in an array

### <font color = 'dodgerblue'> **Differenet data types in arrays**

Common Data types in numpy are :

- bool_	Boolean (True or False) stored as a byte
- int8	Byte (-128 to 127)
- int16	Integer (-32768 to 32767)
- int32	Integer (-2147483648 to 2147483647)
- int64	Integer (-9223372036854775808 to 9223372036854775807)
- uint8	Unsigned integer (0 to 255)
- uint16	Unsigned integer (0 to 65535)
- uint32	Unsigned integer (0 to 4294967295)
- uint64	Unsigned integer (0 to 18446744073709551615)
- float_	Shorthand for float64.
- float16	Half precision float: sign bit, 5 bits exponent, 10 bits mantissa
- float32	Single precision float: sign bit, 8 bits exponent, 23 bits mantissa
- float64	Double precision float: sign bit, 11 bits exponent, 52 bits mantissa


We can check different data types of arrays by using dtype method.

**Syntax**:

 ```
  ndarray.dtype
  ```


In [ ]:
# check the data type of the array

In [ ]:
# check the data type of array generated by using random method

### <font color = 'dodgerblue'> **Determining the memory consumed by arrays** </font>
1. It is important to know that arrays created by numpy take less amount of memory whereas arrays created by lists grasp more memory for storage.
2. itemsize and nbytes are used to determine the storage of an array.
* **itemsize** : It helps to find the length(in bytes) for each array element.

  **Syntax**:

   ```
  ndarray.itemsize
  ```
* **nbytes** : It helps in listing the total length(in bytes) of the array.

  **Syntax**:

    ```
  ndarray.nbytes
  ```

           







#### <font color = 'dodgerblue'> **itemsize**

In [ ]:
#To check the storage in bytes consumed by  each array element

#### <font color = 'dodgerblue'> **nbytes**

In [ ]:
# To check total storage in bytes consumed by a numpy array

## <font color = 'dodgerblue'> **Indexing of arrays** </font>

1. Indexing of arrays is similar to list indexing.
2. We can obtain the array element by mentioning the index number in the square brackets.
3. The indexing always starts from 0.

**Syntax**:



```
  ndarray['enter the index number']
```




In [ ]:
# To access an element from one dimensional array

In [ ]:
# Access an element from the 2 dimensional array by using indexing

## <font color = 'dodgerblue'> **Slicing of arrays** </font>
1. Sometimes, we don't need huge arrays for the computation purpose. We just need a part of the array. These are known as subarrays.
2.  The sub arrays can be acquired by using slicing.
3. Just like an array indexing, we can use the square brackets for slicing the array into a sub array.
4. Hence, Slicing in python means taking elements from one given index to another given index.
  
  **Syntax**:



   ```
      ndarray[start:stop:step]

   ```
  where,


>> **start** : The index number to start the slicing. The default value of start is 0. <br>
 **stop** :The index number to end the slicing. The default value is the size of the dimension. <br>**step** : Integer value which determines the increment between index values in the sequence. By default it takes 1.
  
5. If there is any missing value inside the [start:stop:step] then it takes default value.

**Example** :-

* [: : 2]

  Here ,
  **start** = 0,

  **stop** = size of the dimension,

  **step** = 2

### <font color = 'dodgerblue'> **Access subarrays in one dimension and multiple dimensions**
Slicing is used in similar way for one dimensional and multi dimensional arrays just separated by using commas in multi dimensional arrays.

In [ ]:
# One dimensional sub arrays

In [ ]:
# sub- array consisting first five elements

In [ ]:
# sub-array consisting of last five elements

In [ ]:
# sub-array consisting of the middle elements
# (also note that step size is 2, so we will skip one element)

In [ ]:
# Multi-dimensional sub- arrays

In [ ]:
# get the shape of the array

In [ ]:
# We can access first dimension as rows and second dimension as column

In [ ]:
# get all the rows and first column of the array

In [ ]:
# get all teh columns and first row of the array

In [ ]:
# We can use the syntax :- [start:stop:step] for each dimension separated by comma(,)
# Accessing first two rows and first three columns from multi_array
# let us try to extract first two rows and first three columns

In [ ]:
# Accessing all rows and alternate columns

In [ ]:
# Accessing alternate rows and columns

In [ ]:
# Modifying a subarray modifies the array also
# Let's copy the sub-array from my_arr
# modify subarray

### <font color = 'dodgerblue'> **Creating sub-array by using copy()**
By using copy method we can create a separate copy of the sub- array.
Any changes in the sub- array will not effect the array.

**Syntax**:
```
ndarray[start:stop:step].copy()
```
Following examples explains this method clearly :


In [ ]:
# Let's copy the sub-array from my_arr
# modify subarray

## <font color = 'dodgerblue'> **Reshaping of arrays**</font>

1. Changing the shape of the arrays is important for computation purpose, especially while doing arithmetic operations.
2. This can be done by using reshape() method.

  **Syntax**:


  ```
      ndarray.reshape((mention the size to be given))
  ```


4. In order to convert higher dimensions into the single dimension we can use flatten or ravel functions.

  **Syntax** :


```
    numpy.array.flatten()
    or
    numpy.array.reshape().ravel()
```


### <font color = 'dodgerblue'> **reshape**
- The reshape function returns a new numpy array object that points at the same data.
-  It does not create a copy. This means that modifying one array will also modify the other.

In [ ]:
# create a one dimensional array
# we can check the shape of the given array
# Check the dimension of the num_arr

In [ ]:
# Let us reshape the array, so that it has 3 rows and 3 columns.
# we can check the shape of the given array
# Check the dimension of the num_arr

### <font color = 'dodgerblue'> **ravel**

- The ravel function returns a new one dimensional array object that points at the same data. It also does not create a copy.
- This means that modifying one array will also modify the other.

In [ ]:
# Converting 3 dimensional array into 1 dimension
# Creating a three-dimensional array

In [ ]:
# lets convert this dimension to 1 by using ravel() method
# ravel is useful if you want to convert n-dimensional array to one dimensional array

In [ ]:
# modify the new_array and observe whether it changes my_array

### <font color = 'dodgerblue'> **flatten**

- The flatten function returns a new one dimensional array object.

- flatten always returns a copy. Therefore, in the above example (if we use flatten) changes to new_arr will not affect my_array.


In [ ]:
# Using flatten
# Creating a 3 dimensional random numpy array
# Using ravel to convert it into 1 dimension

In [ ]:
# modify the new_array and observe whether it changes my_array

### <font color = 'dodgerblue'> **unknown size**
In some cases we do not know the size of a particular dimension. In these cases when we specify the shape we can use -1 for that particular dimension. Numpy will infer the size of this dimension.

In [ ]:
# We want to change it to two dimensional array with n rows and 3 columns. Since we do not know
# total number of rows, we can use -1 to specify number of rows

## <font color = 'dodgerblue'> **Stacking arrays**

It is sometimes useful to combine/stack arrays. Numpy provide following methods
  * vstack
  * hstack
  * concatenate
  * stack


In [ ]:
# let us create arrays first

### <font color = 'dodgerblue'> **vstack**
We can stack arrays vertically using vstack. The arrays should have same number of columns. As x1 and x2 has same number of columsn, we can use vstack to combine these arrays.

<img src="https://drive.google.com/uc?export=view&id=15iB5N0WTWnlLHuoOWwJhzTZ_S93a7LX5" width="300"/>

### <font color = 'dodgerblue'> **hstack**
We can stack arrays horizontally using hstack. The arrays should have same number of rows. As x1 and x3 has same number of rows, we can use hstack to combine these arrays.

<img src="https://drive.google.com/uc?export=view&id=1YXSYv1UAdL3HHFcLIl7iuVwuyVsGqFad" width="300"/>

### <font color = 'dodgerblue'> **concatenate**
Concatenate stack arrays along any given axis.
- The arrays must have the same shape (except in the concatenating dimension)
- x1 and x2 have the same shape except for dim = 0, hence we can conactenate these along dim = 0.
- x1 and x3 have the same shape except for dim = 1, hence we can conactenate these along dim = 1
- We cannot concatenate x2 and x3 along any dimension.

  **NOTE:**
  * Concatenation along the rows (axis=0) => Vertical Stacking
  * Concatenation along the columns (axis=1)
  => Horizontal stacking

### <font color = 'dodgerblue'> **stack**
The stack function stacks along a new dimension. All the arrays should have the same shape. We cannot use stack with x1, x2 and x3 as these have differnt shape.


## <font color = 'dodgerblue'> **Splitting arrays**
We can use following metods to split arrays in numpy:
- vsplit - Split arrays vertically (along first axis, axis =0)
- hsplit - Split arrays horizontally (along second axis, axis =1)
- split - aplit arrays along any dimension

### <font color = 'dodgerblue'> **vsplit**
Always splits arrays along first axis (i.e rows for 2 dimensional array)

  Syntax :
  ```
  numpy.vsplit(array,indices_or_sections)
  ```
 where, **indices/sections** are used to mention the number of splits.

In [ ]:
# splitting of an array using vsplit() method
# splitting above array into 2 sub arrays, we will split at indices 2

In [ ]:
# let us try splitting at indices 4
# splitting above array into 2 sub arrays, we will split at indices 4

In [ ]:
# Creating Multiple Splits with vsplit
# splitting above array into 3 subarrays

### <font color = 'dodgerblue'>  **hsplit**
Always splits arrays along second axis (i.e columns for 2 dimensional array)

  Syntax :
  ```
  numpy.hsplit(array,indices_or_sections)
  ```
 where, **indices/sections** are used to mention the number of splits.

In [ ]:
# splitting of an array using hsplit() method
# splitting above array into 2 sub arrays, we will split at indices 2
# let us try splitting at indices 4
# splitting above array into 2 sub arrays, we will split at indices 4

In [ ]:
# Creating Multiple Splits with hsplit
# splitting above array into 3 subarrays

### <font color = 'dodgerblue'> **split()** method :
   * It is used to split the array into sub- arrays along any specified dimension(axis).

  **Syntax** :
  ```
  numpy.split(array, indices_or_sections, axis)
  ```
  where, **indices/sections** are used to mention the number of splits.

In [ ]:
# splitting of an array using split() method
# splitting above array into 5 sub-arrays

# <font color = 'dodgerblue'> **Numpy's Universal functionas (ufuncs)**

* ufuncs stands for "Universal Functions".  They are vectorized wrappers of simple functions.
* There are two types of UFuncs, they are **unary ufuncs** (operate on a single input) and **binary Ufuncs** (operate on two inputs).

## <font color = 'dodgerblue'>  **binary ufuncs**
* This include all arithmetic operators (+, -, *, /, //, **, etc.) and some other functions (add, greater, maximum etc,). They apply elementwise on two ndarrays. These can also be used when arrays have different shape (see Broadcasting).




## <font color = 'dodgerblue'>  **unary ufuncs**
They are fast elementwise functions that apply to all the elements of a single array. For example, when we apply  square function to an array, the finction returns a new ndarray where all the elemnets are squared.

# <font color = 'dodgerblue'> **Broadcasting**
The way NumPy handles arrays with different shapes while performing arithmetic operations is known as broadcasting. The smaller array is "broadcast" across the larger array, subject to specific conditions.

* The following image describes how a 2 dimensional tensor will be added to a 1 dimensional tensor
<img src="https://drive.google.com/uc?export=view&id=1QG2GO1owGpyXbcugJFVFGb4o_buV4s3j" width="600"/>

## <font color = 'dodgerblue'> **Rules of broadcasting**</font>
1. If two arrays differ in their sizes (i.e they have different number of dimensions), the array with the smaller dimension can be appended with '1' to the left in its shape. In other words, the array is transformed to a two-dimensional array.
2. Again if the shape of the array does not match, then the transformed array (which has shape equal to 1) will be stretched out to match the shape of the array of higher dimension.
We can check the above figure for this.
2. When operating on two arrays, NumPy compares their shapes
 element-wise. It starts with the trailing dimensions and works its way forward. Two dimensions are compatible when

   * They are equal, or

   * One of them is 1
2. If any dimension of the arrays does not match and  neither is equal to 1, then we get an error.



### <font color = 'dodgerblue'> **Implementation of Broadcasting**

In [ ]:
# Consider 2 matrices A and B
# Checking the shape of both matrices

B has one dimension and A has two dimensions. Numpy will first prepend 1 to the dimension of A so that it also has same number of dimensions.

In [ ]:
# Reshaping matrix B to 2 dimensional array

After reshaping, the shape of B still dosen't match to A. Now it will stretch the tensor with smaller dimension so that it has the same shape as the tensor with higher dimensions.

In [ ]:
# Stretching matrix B along the rows

Finally, after stretching matrix B thrice along the rows, the shape becomes equal to that of matrix A. Let's add both the matrices and check the result:

Comparing the result of addition of matrix A and stretched matrix B with original matrices A and B:

We can see that both the results match. This example shows what numpy does under the hood to do mathematical operations on arrays of different shapes. So broadcasting is an efficient way of performing operations on arrays of unequal sizes

### <font color = 'dodgerblue'> **Broadcasting Examples**

Consider the following example :

 $$A=\begin{bmatrix} 1 & 2 & 4 \\ 4 & 1 & 3\end{bmatrix}$$

 $$B=\begin{bmatrix} 1 & 2 & 4 \end{bmatrix}$$

*  We can observe that shape of A is(2, 3) and shape of B is (3, ) [if there is a single row, we can mention the shape by using number of columns separated by a comma(,)]
* Here B is an array with fewer dimensions.
* By rule 1, Numpy will first prepend 1 to the dimension of B so that it also has same number of dimensions.:
     
    So, B shape is (1, 3)
* Now, let's check the shape again :
   
     A = (2, 3) and B = (1, 3)
* We can see that all the corresponding dimensions of two arrays are either of the same size or one of the dimension is 1. Hence the arrays are broadcastable and we can do mathamatical opeartions on these arrays.

In [ ]:
# we can check that the arrays are broadcastable by doing arithmatic operations

QUIZ: Consider following two arrays:
- arr1 = np.arange(4).reshape((4,1))
- arr2 = np.arange(3)

1. Can we take the product of these two arrays?
2.  What is the shape of the final array?

In [ ]:
# Create arrays
#check the shape of the arrays

In [ ]:
# array2 has fewer number of dimensions
# We can prepend 1 on the left side , the hsape of array 2 will ne (1, 3)
# If we compare the arrays, we can see that they follow broadcasting rules.
# Hence we can take product.
# The shape of the new array will be (4,3)

<font color = 'red'> **In summary:** </font> <font color = 'aqua'> Two arrays are “broadcastable” if the following rules hold:

When iterating over the dimension sizes, starting at the trailing dimension, the dimension sizes must either be equal or one of them should be 1.
Else, they are not broadcastable.</font>

# <font color = 'dodgerblue'> **Aggregate functions**

* These are ndarray methods that compute the aggregate value (like mean, min, sum, product, variance, any, all) of all the elements of ndarray or aggregate value along a particulat axis (for example for 2 d- dimensional ndarrays we can compute the mean along rows or columns).





## <font color = 'dodgerblue'> **aggregate all values**

## <font color = 'dodgerblue'> **aggregate along a dimension**

In [ ]:
# For multidimensional array, we can aggrgate along a specific dimension as well

Let us say we want to divide all the elements of a row with the column sum for that row. The shape of original array (2, 3) and the column sum (2,) are not compatible (we cannot bradcast these two arrays). If we try this operation it will give us an error.

## <font color = 'dodgerblue'> **keepdims**

In the above example the number of dimensions reduces after aggregation. If we want to keep the number of dimesnions same as as original array, we can pass the argument keepdims= True.

In [ ]:
# keep number of dimensions same by passing keepdims = True

We can see that now the shapes of the original array and column sum are broadcastable.

# <font color = 'dodgerblue'> **Matrix - 2 Dimensional arrays**
* A matrix is a rectangular arrays of numbers, symbols, or expressions, arranged in rows and columns.
* A matrix with $m$ rows and $n$ columns is called $
m * n$ (or) $m$ by  $n$ matrix. Where $m$ and $n$ are called dimensions.
* The following matrix is an example of $m$ by $n$ matrix ($m$ rows and $n$ columns )
\begin{bmatrix}
x_{1,1} & x_{1,2} & \cdots & x_{1,n} \\ x_{2,1} & x_{2,2}&\cdots& x_{2,n}  \\\vdots & \vdots & \ddots & \vdots \\ x_{m,1} & x_{m,2} &\cdots& x_{m,n} \end{bmatrix}

## <font color = 'dodgerblue'> **Matrix addition**
* Suppose we have two matrices and they are

$\boldsymbol{A} = \begin{bmatrix}
1 & 2 & 3\\5 & 6 & 4\\4 & 4 & 7\end{bmatrix}$
$\boldsymbol{B} = \begin{bmatrix}
5& 7& 3\\8& 9 & 10\\4& 3 & 9\end{bmatrix}$
* We can find the **sum of matrices** simply by adding the corresponding entries in matrices $A$ and $B$.

  Therefore, $A+B =  \begin{bmatrix}
  1+5 & 2+7 & 3+3\\5+8 & 6+9 & 4+10\\4+4 & 4+3 & 7+9\end{bmatrix}$
    
  $=\begin{bmatrix}
  6 & 9 & 6\\13 & 15 & 14\\8 & 7 & 16\end{bmatrix}$

* In numpy, we can use **add()** method to perform addition of matrices.

In [ ]:
# Addition of matrices by using add() method

## <font color = 'dodgerblue'> **Matrix Subtraction**
* We can find the **difference between matrices** simply by subtracting the corresponding entries in matrices $A$ and $B$.
* Let's consider the above two matrices $A$ and $B$.
Therefore, $A-B =  \begin{bmatrix}
1-5 & 2-7 & 3-3\\5-8 & 6-9 &4-10\\4-4 & 4-3 & 7-9\end{bmatrix}$
$\ =\begin{bmatrix}
-4 & -5 &  0\\-3 &-3 & -6\\  0 &  1 & -2\end{bmatrix}$


* In numpy, we can use **subtract()** method to subtract two matrices.

In [ ]:
#finding the difference between the two matrices by using subtract() method.

## <font color = 'dodgerblue'> **Hadamard product**
* Hadamard product of two vectors is very similar to matrix addition, elements corresponding to same row and columns of given vectors/matrices are multiplied together to form a new vector/matrix.
* It is named after French Mathematician, **Jacques Hadamard**.

* **Example :** If we have two matrices A and B. The size of $A$ = (2, 2) and $B$ = (2, 2) then the hadamard product of $A$, $B$ denoted as
$A \circ B$  will be of size (2, 2).


$\boldsymbol{A} = \begin{bmatrix}
1& 2 & 3\\5&  6 & 4\end{bmatrix}$
$\boldsymbol{B} = \begin{bmatrix}
5& 7& 3\\8& 9 & 10\end{bmatrix}$

$\\(A \circ B)$ =
$\begin{bmatrix}1×5 & 2×7 & 3×3\\5×8 & 6×9 & 4×10\end{bmatrix}$
= $\begin{bmatrix}5 & 14 & 9\\40 & 54 & 40\end{bmatrix}$

* In numpy, we can use **multiply()** method or **operator *** to find the hadamard product.





In [ ]:
#Let's create the above example matrices using numpy
#the hadamard product for the above two matrices is given as follows :
# We can see the element wise product for the two matrices

## <font color = 'dodgerblue'> **Trace of a matrix**
* In linear algebra, the trace of a square matrix A, denoted by  **tr(A)**
* It is defined to be the sum of elements on the main diagonal (from the upper left to the lower right) of A.
* **Example** :- **trace of matrix A** is given below :-

$\bf{A} =
  \begin{pmatrix}
    a_{11} & a_{12} & a_{13} \\
    a_{21} & a_{22} & a_{23} \\
    a_{31} & a_{32} & a_{33}
  \end{pmatrix}$
  $= \begin{pmatrix}
    1 &  5 &  3 \\
    11 &  10 &  7 \\
     6 & 12 & -2
  \end{pmatrix}$

  Then the trace of $A$ is given as :-

  $\operatorname{tr}({A}) = \sum_{i=1}^{3} a_{ii} = a_{11} + a_{22} + a_{33} = 1 + 10 + (-2) = 9$

* In numpy, we can find the trace of a matrix by using trace() method.

In [ ]:
#matrix A

In [ ]:
# Trace of matrix

## <font color = 'dodgerblue'> **Transpose of a matrix**
* In linear algebra, the transpose of a matrix is an operator which flips a matrix over its diagonal.
* That is, it switches the row and column indices of the matrix $A$ by producing another matrix, it is often denoted by $A^T$.
* **Example** - Let us take a matrix

  $\boldsymbol{A} = \begin{bmatrix}
  1& 2 \\5&  6 \end{bmatrix}$

  Then the transpose of A is given as follows :-

  $\boldsymbol{A^T} = \begin{bmatrix}
  1& 5 \\2&  6 \end{bmatrix}$

* In numpy, we can use **T** in order to transpose a matrix. Let's check an example of matrix transpose using numpy as follows :-

In [ ]:
# Using transpose of a matrix by using T in numpy

In [ ]:
# We can check the tranpose of the matrix A

## <font color = 'dodgerblue'> **Inner product or Dot product**
Dot product of 2 vectors x and y, represented as `(x.T)(y)` is given by the summation of product of elements at the same position.

If we have 2 vectors x: [1, 2, 3, 4] and y: [1, 1, 2, 1]

(x.y) will be 1x1 + 2x1 + 3x2 + 4x1 = 13

To find the inner product of the vectors, we can use the dot() method of NumPy.

In [ ]:
# Inner product of vectors
# if arrays are of the same length then inner product will be a scalar

## <font color = 'dodgerblue'> **Matrix multiplication**</font>
Matrix multiplication is a binary operation on 2 matrices which gives us a matrix which is the product of the 2 matrices.

If we are given 2 matrices $A$ of shape $(m * n)$ and $B$ of shape $(q * p)$, we can perform matrix multiplication only when $n = q$ and the resultant product matrix will have shape $(m * p)$.

Suppose we are given 2 matrices $A (m * n)$ and $B (n * p)$:

$$\mathbf{A}=\begin{bmatrix}
 a_{11} & a_{12} & \cdots & a_{1n} \\
 a_{21} & a_{22} & \cdots & a_{2n} \\
\vdots & \vdots & \ddots & \vdots \\
 a_{m1} & a_{m2} & \cdots & a_{mn} \\
\end{bmatrix},\quad
\mathbf{B}=\begin{bmatrix}
 b_{11} & b_{12} & \cdots & b_{1p} \\
 b_{21} & b_{22} & \cdots & b_{2p} \\
\vdots & \vdots & \ddots & \vdots \\
 b_{n1} & b_{n2} & \cdots & b_{np} \\
\end{bmatrix}$$

Then after performing matrix multiplication, the resultant matrix C = AB will be:

$$\mathbf{C}=\begin{bmatrix}
 c_{11} & c_{12} & \cdots & c_{1p} \\
 c_{21} & c_{22} & \cdots & c_{2p} \\
\vdots & \vdots & \ddots & \vdots \\
 c_{mp} & c_{mp} & \cdots & c_{mp} \\
\end{bmatrix}$$

Here, $c_{ij} = a_{i1}b_{1j} + a_{i2}b_{2j} + ... a_{in}b_{b_nj} = \sum_{k = 1}^n a_{ik}b_{kj}$

for, $i = 1,....m$ and $j = 1,...p$


Thus, each element of C, $c_{ij}$ is obtained by dot product of $i^{th}$ row of $A$ and $j^{th}$ column of $B$.

**Example** :
  1. Let $A$ be a matrix of (4, 3) dimensions.
  2. Let $B$ be another matrix of (3, 2) dimensions.
  3. Let us denote denote the matrix multiplication of $A$ and $B$ with $C$.
  5. Then the dimension of $C$ = (number of rows of $A$,number of columns of $B$)
     
    dimension of  $C$ = (4, 2)

The figure given below will give a good example of matrix multplication :

<img src = "https://drive.google.com/uc?view=export&id=176DF50XdtwkqU5wvxtWuD75sRDHvSJBf" width ="250"/>

In [ ]:
# let's consider two matrices of different shape

In [ ]:
# Let's the check the rule of matrix multiplication
# Since, the number of columns of x = number of rows of y
# the shape of the product of both matrix is (number of rows of x, number of columns of y)
# the matmul() method helps in multiplying matrices

## <font color = 'dodgerblue'> **Outer product**

* If $H$ and $M$ are column vectors of any size, then $H M^T$ is the
outer product of $H$ and $M$.
* Example: $\boldsymbol{H} = \begin{bmatrix}
1\\7\\5\end{bmatrix}$
$\boldsymbol{M} = \begin{bmatrix}
2\\4\\ 9\end{bmatrix}$

  **H** and **M** are column vectors, each having 3 elements.

  **H'** is the transpose of **H**, which makes **H'** a row vector,

  **M'** is the transpose of **M**, which makes **M'** a row vector.


* We can apply the matrix multiplication rule and check the required dimension.

Now, the outer product of the matrix is defined as follows :-

$HM' =  \begin{bmatrix}
1\\ 7\\ 5\end{bmatrix} × \begin{bmatrix}
2\ 4\ 9\end{bmatrix}$ = $\begin{bmatrix}1×2 & 1×4 & 1×9 \\7×2 & 7×4 & 7×9\\5×2 & 5×4 & 5×9\end{bmatrix}$
= $\begin{bmatrix}2 & 4 & 9 \\14 & 28 & 63\\10 & 20 & 45\end{bmatrix}$



The outer product of the vectors and matrices can be found using the outer() method of NumPy.

**Syntax**


```
numpy.outer(a, b, out = None)
```
where a, b are the vectors  or matrices.
out = A location where the result is stored(optional argument)



In [ ]:
#let's consider above example
#let a be a column matrix
#b be a row matrix
#the outer product of the matrices are

## <font color = 'dodgerblue'> **Inverse of matrix**
Wikipedia Definition (https://en.wikipedia.org/wiki/Invertible_matrix)<br><br>
In linear algebra, an n-by-n square matrix $\mathbf{A}$ is called invertible (also nonsingular or nondegenerate), if there exists an $n$ by $n$ square matrix $\mathbf{B}$ such that
\begin{equation}
  \mathbf{A}\mathbf{B} = \mathbf{B}\mathbf{A} = \mathbf{I_n}
\end{equation}

where $\mathbf{I_n}$ denotes the n-by-n identity matrix and the multiplication used is ordinary matrix multiplication. If this is the case, then the matrix $\mathbf{B}$ is uniquely determined by $\mathbf{A}$, and is called the (multiplicative) inverse of $\mathbf{A}$, denoted by $\mathbf{A^{-1}}$

In [ ]:
# Let's create an 1-D array

In [ ]:
# inverse of the matrix

In [ ]:
# let us check teh condition A A_inv = I